$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: jtvae_pipeline
description: Pipeline for jtvae training.

jobs:
  vocabulary_generation:
    type: command
    inputs:
      total_vocab: 
        type: uri_file
        path: azureml://datastores/workspaceblobstore/paths/UI/2024-02-24_021817_UTC/scaffold_split_25perc_total.txt
    outputs:
      total_vocab_paper: 
        type: uri_file
        mode: upload
    code: src
    environment: azureml:CPU_JTVAE:1
    compute: azureml:overhulsejm4
    command: >-
      ./script-vocab.sh ${{inputs.total_vocab}} ${{outputs.total_vocab_paper}}
      
  preprocess:
    type: command
    inputs:
      total_train_set: 
        type: uri_file
        path: azureml:coconut_220K_train:1
    outputs:
      preprocessed_train_set_details: 
        mode: upload
        type: uri_file
      preprocessed_train_set_pkl: 
        type: uri_folder
        mode: upload
    code: src
    environment: azureml:CPU_JTVAE:1
    compute: azureml:overhulsejm4
    command: >-
      ./script-preprocess.sh ${{inputs.total_train_set}} ${{outputs.preprocessed_train_set_details}} ${{outputs.preprocessed_train_set_pkl}}
